In [1]:
#!/bin/bash
!kaggle datasets download rikdifos/credit-card-approval-prediction

Warning: Looks like you're using an outdated `kaggle` version (installed: 2.0.2), please consider upgrading to the latest version (2.2.2)
Dataset URL: https://www.kaggle.com/datasets/rikdifos/credit-card-approval-prediction
License(s): CC0-1.0
Downloading credit-card-approval-prediction.zip to /content
100% 5.32M/5.32M [00:00<00:00, 110MB/s]

In [2]:
!unzip credit-card-approval-prediction.zip

Archive:  credit-card-approval-prediction.zip
  inflating: application_record.csv
  inflating: credit_record.csv

In [3]:
import pandas as pd
import numpy as np

In [4]:
df = pd.read_csv('/content/application_record.csv')
df

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,NaN,2.0
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438552,6840104,M,N,Y,0,135000.0,Pensioner,Secondary / secondary special,Separated,House / apartment,-22717,365243,1,0,0,0,NaN,1.0
438553,6840222,F,N,N,0,103500.0,Working,Secondary / secondary special,Single / not married,House / apartment,-15939,-3007,1,0,0,0,Laborers,1.0
438554,6841878,F,N,N,0,54000.0,Commercial associate,Higher education,Single / not married,With parents,-8169,-372,1,1,0,0,Sales staff,1.0
438555,6842765,F,N,Y,0,72000.0,Pensioner,Secondary / secondary special,Married,House / apartment,-21673,365243,1,0,0,0,NaN,2.0
438556,6842885,F,N,Y,0,121500.0,Working,Secondary / secondary special,Married,House / apartment,-18858,-1201,1,0,1,0,Sales staff,2.0

In [5]:
# 1. Dataset haqqında ümumi məlumat
# df.shape ilə sətir və sütun sayını tap
# df.info() ilə sütunların data tiplərinə bax
# df.describe() ilə statistik göstəriciləri analiz et

In [6]:
df.shape

(438557, 18)

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 438557 entries, 0 to 438556
Data columns (total 18 columns):
 #   Column               Non-Null Count   Dtype
---  ------               --------------   -----
 0   ID                   438557 non-null  int64
 1   CODE_GENDER          438557 non-null  object
 2   FLAG_OWN_CAR         438557 non-null  object
 3   FLAG_OWN_REALTY      438557 non-null  object
 4   CNT_CHILDREN         438557 non-null  int64
 5   AMT_INCOME_TOTAL     438557 non-null  float64
 6   NAME_INCOME_TYPE     438557 non-null  object
 7   NAME_EDUCATION_TYPE  438557 non-null  object
 8   NAME_FAMILY_STATUS   438557 non-null  object
 9   NAME_HOUSING_TYPE    438557 non-null  object
 10  DAYS_BIRTH           438557 non-null  int64
 11  DAYS_EMPLOYED        438557 non-null  int64
 12  FLAG_MOBIL           438557 non-null  int64
 13  FLAG_WORK_PHONE      438557 non-null  int64
 14  FLAG_PHONE           438557 non-null  int64
 15  FLAG_EMAIL           438557 non-null  int64
 16  OCCUPATION_TYPE      304354 non-null  object
 17  CNT_FAM_MEMBERS      438557 non-null  float64
dtypes: float64(2), int64(8), object(8)
memory usage: 60.2+ MB

In [8]:
df.describe()

,ID,CNT_CHILDREN,AMT_INCOME_TOTAL,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,CNT_FAM_MEMBERS
count,4.385570e+05,438557.000000,4.385570e+05,438557.000000,438557.000000,438557.0,438557.000000,438557.000000,438557.000000,438557.000000
mean,6.022176e+06,0.427390,1.875243e+05,-15997.904649,60563.675328,1.0,0.206133,0.287771,0.108207,2.194465
std,5.716370e+05,0.724882,1.100869e+05,4185.030007,138767.799647,0.0,0.404527,0.452724,0.310642,0.897207
min,5.008804e+06,0.000000,2.610000e+04,-25201.000000,-17531.000000,1.0,0.000000,0.000000,0.000000,1.000000
25%,5.609375e+06,0.000000,1.215000e+05,-19483.000000,-3103.000000,1.0,0.000000,0.000000,0.000000,2.000000
50%,6.047745e+06,0.000000,1.607805e+05,-15630.000000,-1467.000000,1.0,0.000000,0.000000,0.000000,2.000000
75%,6.456971e+06,1.000000,2.250000e+05,-12514.000000,-371.000000,1.0,0.000000,1.000000,0.000000,3.000000
max,7.999952e+06,19.000000,6.750000e+06,-7489.000000,365243.000000,1.0,1.000000,1.000000,1.000000,20.000000

In [9]:
# 2. Missing Value Analizi
# Hər sütunda neçə null dəyər olduğunu tap
# Null dəyərlərin faizini hesabla
# OCCUPATION_TYPE sütunundakı null dəyərləri doldur

In [10]:
df.isna().sum()

ID                          0
CODE_GENDER                 0
FLAG_OWN_CAR                0
FLAG_OWN_REALTY             0
CNT_CHILDREN                0
AMT_INCOME_TOTAL            0
NAME_INCOME_TYPE            0
NAME_EDUCATION_TYPE         0
NAME_FAMILY_STATUS          0
NAME_HOUSING_TYPE           0
DAYS_BIRTH                  0
DAYS_EMPLOYED               0
FLAG_MOBIL                  0
FLAG_WORK_PHONE             0
FLAG_PHONE                  0
FLAG_EMAIL                  0
OCCUPATION_TYPE        134203
CNT_FAM_MEMBERS             0
dtype: int64

In [11]:
len(df)

438557

In [12]:
(df.isna().sum()/len(df))*100

ID                      0.000000
CODE_GENDER             0.000000
FLAG_OWN_CAR            0.000000
FLAG_OWN_REALTY         0.000000
CNT_CHILDREN            0.000000
AMT_INCOME_TOTAL        0.000000
NAME_INCOME_TYPE        0.000000
NAME_EDUCATION_TYPE     0.000000
NAME_FAMILY_STATUS      0.000000
NAME_HOUSING_TYPE       0.000000
DAYS_BIRTH              0.000000
DAYS_EMPLOYED           0.000000
FLAG_MOBIL              0.000000
FLAG_WORK_PHONE         0.000000
FLAG_PHONE              0.000000
FLAG_EMAIL              0.000000
OCCUPATION_TYPE        30.601039
CNT_FAM_MEMBERS         0.000000
dtype: float64

In [13]:
df['OCCUPATION_TYPE'].mode()[0]

'Laborers'

In [14]:
df.fillna(df['OCCUPATION_TYPE'].mode()[0], inplace=True)

In [15]:
# 3. Duplicate Analizi
# Datasetdə neçə duplicate sətr var onu tap
# Duplicate sətrləri sil
# Silinmədən əvvəl və sonra dataset ölçüsünü müqayisə et

In [16]:
df.duplicated().sum()

np.int64(0)

In [17]:
# 4. Data Type və Yeni Sütunlar
# DAYS_BIRTH sütunundan Age sütunu yarat
# DAYS_EMPLOYED sütunundan Work_Years sütunu yarat
# Yeni sütunların düzgün işlədiyini yoxla

In [18]:
df['Age'] = df['DAYS_BIRTH'].abs()//365
df['Work_Years'] = df['DAYS_EMPLOYED'].abs()//365
df.head()

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,Age,Work_Years
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Laborers,2.0,32,12
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Laborers,2.0,32,12
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0,58,3
3,5008808,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,52,8
4,5008809,F,N,Y,0,270000.0,Commercial associate,Secondary / secondary special,Single / not married,House / apartment,-19110,-3051,1,0,1,1,Sales staff,1.0,52,8

In [19]:
# 5. Kategorik Məlumatların Təhlili
# Gender üzrə paylanmanı tap (M / F)
# Ən çox rast gəlinən peşəni tap
# Ən çox rast gəlinən təhsil səviyyəsini tap
# Ailə vəziyyətlərinin paylanmasını analiz et

In [20]:
df['CODE_GENDER'].value_counts()

CODE_GENDER
F    294440
M    144117
Name: count, dtype: int64

In [21]:
df['OCCUPATION_TYPE'].mode()

0    Laborers
Name: OCCUPATION_TYPE, dtype: object

In [22]:
df['NAME_EDUCATION_TYPE'].mode()

0    Secondary / secondary special
Name: NAME_EDUCATION_TYPE, dtype: object

In [23]:
df['NAME_FAMILY_STATUS'].value_counts()

NAME_FAMILY_STATUS
Married                 299828
Single / not married     55271
Civil marriage           36532
Separated                27251
Widow                    19675
Name: count, dtype: int64

In [24]:
# 6. Gəlir Təhlili
# Ümumi orta gəliri tap
# Minimum və maksimum gəliri tap
# Peşələr üzrə orta gəliri hesabla
# Təhsil səviyyəsinə görə orta gəliri müqayisə et
# Gender üzrə orta gəliri müqayisə et

In [25]:
df['AMT_INCOME_TOTAL'].mean()

np.float64(187524.2860095039)

In [26]:
df['AMT_INCOME_TOTAL'].min()

26100.0

In [27]:
df['AMT_INCOME_TOTAL'].max()

6750000.0

In [28]:
df.groupby('NAME_EDUCATION_TYPE')['AMT_INCOME_TOTAL'].mean()

NAME_EDUCATION_TYPE
Academic degree                  240692.307692
Higher education                 226106.872502
Incomplete higher                207331.018315
Lower secondary                  143933.865218
Secondary / secondary special    172056.654071
Name: AMT_INCOME_TOTAL, dtype: float64

In [29]:
df.groupby('OCCUPATION_TYPE')['AMT_INCOME_TOTAL'].mean()

OCCUPATION_TYPE
Accountants              215137.274977
Cleaning staff           147064.463815
Cooking staff            155848.425334
Core staff               190905.844378
Drivers                  202065.242047
HR staff                 203620.686047
High skill tech staff    195712.011010
IT staff                 210958.733444
Laborers                 174182.916010
Low-skill Laborers       150334.309346
Managers                 282125.938701
Medicine staff           168102.197707
Private service staff    201600.651042
Realty agents            223510.806916
Sales staff              170912.759267
Secretaries              169456.878669
Security staff           169835.113662
Waiters/barmen staff     158796.621622
Name: AMT_INCOME_TOTAL, dtype: float64

In [30]:
df.groupby('CODE_GENDER')['AMT_INCOME_TOTAL'].mean()

CODE_GENDER
F    174523.040910
M    214086.638868
Name: AMT_INCOME_TOTAL, dtype: float64

In [31]:
# 7. Filter əməliyyatları
# Gəliri 300000-dən böyük olan müştəriləri seç
# Evli olan şəxsləri filterlə
# Ali təhsilli şəxsləri seç
# Həm işləyən, həm avtomobili olan şəxsləri tap

In [32]:
df[df['AMT_INCOME_TOTAL']>300000]

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,Age,Work_Years
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Laborers,2.0,32,12
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Laborers,2.0,32,12
29,5008838,M,N,Y,1,405000.0,Commercial associate,Higher education,Married,House / apartment,-11842,-2016,1,0,0,0,Managers,3.0,32,5
30,5008839,M,N,Y,1,405000.0,Commercial associate,Higher education,Married,House / apartment,-11842,-2016,1,0,0,0,Managers,3.0,32,5
31,5008840,M,N,Y,1,405000.0,Commercial associate,Higher education,Married,House / apartment,-11842,-2016,1,0,0,0,Managers,3.0,32,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438530,6836990,M,N,N,0,360000.0,Commercial associate,Higher education,Separated,House / apartment,-16374,-606,1,0,0,0,Managers,1.0,44,1
438531,6836991,F,N,N,0,360000.0,Commercial associate,Higher education,Separated,House / apartment,-16374,-606,1,0,0,0,Managers,1.0,44,1
438532,6836995,F,N,N,0,360000.0,Commercial associate,Higher education,Separated,House / apartment,-16374,-606,1,0,0,0,Managers,1.0,44,1
438542,6837905,M,Y,Y,1,355050.0,Working,Secondary / secondary special,Married,House / apartment,-15904,-2614,1,0,0,0,Laborers,3.0,43,7
438543,6837906,M,Y,Y,1,355050.0,Working,Secondary / secondary special,Married,House / apartment,-15904,-2614,1,0,0,0,Laborers,3.0,43,7

In [33]:
df['NAME_FAMILY_STATUS'].unique()

array(['Civil marriage', 'Married', 'Single / not married', 'Separated',
       'Widow'], dtype=object)

In [34]:
df[(df['NAME_FAMILY_STATUS'] == 'Married')|(df['NAME_FAMILY_STATUS'] =='Civil marriage')]

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,Age,Work_Years
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Laborers,2.0,32,12
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Laborers,2.0,32,12
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0,58,3
10,5008815,M,Y,Y,0,270000.0,Working,Higher education,Married,House / apartment,-16872,-769,1,1,1,1,Accountants,2.0,46,2
11,5112956,M,Y,Y,0,270000.0,Working,Higher education,Married,House / apartment,-16872,-769,1,1,1,1,Accountants,2.0,46,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438544,6838056,F,N,Y,0,135000.0,State servant,Secondary / secondary special,Married,House / apartment,-18997,-483,1,0,0,0,Laborers,2.0,52,1
438547,6839917,F,N,Y,0,180000.0,Pensioner,Higher education,Married,House / apartment,-10966,-2704,1,0,0,0,Laborers,2.0,30,7
438548,6839936,M,Y,Y,1,135000.0,Working,Secondary / secondary special,Married,House / apartment,-12569,-2095,1,0,0,0,Laborers,3.0,34,5
438555,6842765,F,N,Y,0,72000.0,Pensioner,Secondary / secondary special,Married,House / apartment,-21673,365243,1,0,0,0,Laborers,2.0,59,1000
438556,6842885,F,N,Y,0,121500.0,Working,Secondary / secondary special,Married,House / apartment,-18858,-1201,1,0,1,0,Sales staff,2.0,51,3

In [35]:
df['NAME_EDUCATION_TYPE'].unique()

array(['Higher education', 'Secondary / secondary special',
       'Incomplete higher', 'Lower secondary', 'Academic degree'],
      dtype=object)

In [36]:
df[df['NAME_EDUCATION_TYPE']=='Higher education']

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,Age,Work_Years
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Laborers,2.0,32,12
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Laborers,2.0,32,12
7,5008812,F,N,Y,0,283500.0,Pensioner,Higher education,Separated,House / apartment,-22464,365243,1,0,0,0,Laborers,1.0,61,1000
8,5008813,F,N,Y,0,283500.0,Pensioner,Higher education,Separated,House / apartment,-22464,365243,1,0,0,0,Laborers,1.0,61,1000
9,5008814,F,N,Y,0,283500.0,Pensioner,Higher education,Separated,House / apartment,-22464,365243,1,0,0,0,Laborers,1.0,61,1000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438533,6837198,F,N,N,0,211500.0,Pensioner,Higher education,Separated,House / apartment,-20490,365243,1,0,0,0,Laborers,1.0,56,1000
438536,6837264,F,N,N,2,90000.0,State servant,Higher education,Single / not married,House / apartment,-16062,-1275,1,0,0,0,Core staff,4.0,44,3
438541,6837707,M,N,Y,0,202500.0,Working,Higher education,Civil marriage,House / apartment,-13510,-2309,1,1,0,0,Laborers,2.0,37,6
438547,6839917,F,N,Y,0,180000.0,Pensioner,Higher education,Married,House / apartment,-10966,-2704,1,0,0,0,Laborers,2.0,30,7
438554,6841878,F,N,N,0,54000.0,Commercial associate,Higher education,Single / not married,With parents,-8169,-372,1,1,0,0,Sales staff,1.0,22,1

In [37]:
df[(df['FLAG_OWN_CAR']=='Y')&(df['NAME_INCOME_TYPE']=='Working')]

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,Age,Work_Years
0,5008804,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Laborers,2.0,32,12
1,5008805,M,Y,Y,0,427500.0,Working,Higher education,Civil marriage,Rented apartment,-12005,-4542,1,1,0,0,Laborers,2.0,32,12
2,5008806,M,Y,Y,0,112500.0,Working,Secondary / secondary special,Married,House / apartment,-21474,-1134,1,0,0,0,Security staff,2.0,58,3
10,5008815,M,Y,Y,0,270000.0,Working,Higher education,Married,House / apartment,-16872,-769,1,1,1,1,Accountants,2.0,46,2
11,5112956,M,Y,Y,0,270000.0,Working,Higher education,Married,House / apartment,-16872,-769,1,1,1,1,Accountants,2.0,46,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
438518,6835982,M,Y,Y,0,135000.0,Working,Incomplete higher,Married,House / apartment,-15293,-5244,1,1,1,0,Laborers,2.0,41,14
438519,6836039,M,Y,N,0,157500.0,Working,Higher education,Married,House / apartment,-11619,-4149,1,0,0,0,Core staff,2.0,31,11
438542,6837905,M,Y,Y,1,355050.0,Working,Secondary / secondary special,Married,House / apartment,-15904,-2614,1,0,0,0,Laborers,3.0,43,7
438543,6837906,M,Y,Y,1,355050.0,Working,Secondary / secondary special,Married,House / apartment,-15904,-2614,1,0,0,0,Laborers,3.0,43,7
438548,6839936,M,Y,Y,1,135000.0,Working,Secondary / secondary special,Married,House / apartment,-12569,-2095,1,0,0,0,Laborers,3.0,34,5

In [38]:
# 8. GroupBy analizləri
# Peşələr üzrə müştəri sayını tap
# Təhsil səviyyəsinə görə orta gəliri hesabla
# Gender üzrə orta gəliri hesabla
# Mənzil tipinə görə müştəri sayını tap

In [39]:
df['OCCUPATION_TYPE'].value_counts()

OCCUPATION_TYPE
Laborers                 212443
Core staff                43007
Sales staff               41098
Managers                  35487
Drivers                   26090
High skill tech staff     17289
Accountants               15985
Medicine staff            13520
Cooking staff              8076
Security staff             7993
Cleaning staff             5845
Private service staff      3456
Low-skill Laborers         2140
Secretaries                2044
Waiters/barmen staff       1665
Realty agents              1041
HR staff                    774
IT staff                    604
Name: count, dtype: int64

In [40]:
df['NAME_HOUSING_TYPE'].value_counts()

NAME_HOUSING_TYPE
House / apartment      393831
With parents            19077
Municipal apartment     14214
Rented apartment         5974
Office apartment         3922
Co-op apartment          1539
Name: count, dtype: int64

In [41]:
#general
# Datasetdə ən çox hansı peşə var?
# Ən yüksək gəlir hansı peşədədir?
# Təhsil gəlirə təsir edirmi?
# Gender üzrə gəlir fərqi varmı?
# Yaş ilə gəlir arasında əlaqə varmı?
# İş stajı ilə gəlir arasında əlaqə varmı?

In [42]:
df[df['AMT_INCOME_TOTAL'] == df['AMT_INCOME_TOTAL'].max()]

,ID,CODE_GENDER,FLAG_OWN_CAR,FLAG_OWN_REALTY,CNT_CHILDREN,AMT_INCOME_TOTAL,NAME_INCOME_TYPE,NAME_EDUCATION_TYPE,NAME_FAMILY_STATUS,NAME_HOUSING_TYPE,DAYS_BIRTH,DAYS_EMPLOYED,FLAG_MOBIL,FLAG_WORK_PHONE,FLAG_PHONE,FLAG_EMAIL,OCCUPATION_TYPE,CNT_FAM_MEMBERS,Age,Work_Years
228159,5987963,M,Y,N,0,6750000.0,Working,Higher education,Married,House / apartment,-19341,-443,1,1,1,0,Laborers,2.0,52,1
228160,5987964,M,Y,N,0,6750000.0,Working,Higher education,Married,House / apartment,-19341,-443,1,1,1,0,Laborers,2.0,52,1
228161,5987966,M,Y,N,0,6750000.0,Working,Higher education,Married,House / apartment,-19341,-443,1,1,1,0,Laborers,2.0,52,1
228162,5987967,M,Y,N,0,6750000.0,Working,Higher education,Married,House / apartment,-19341,-443,1,1,1,0,Laborers,2.0,52,1
228163,5987968,M,Y,N,0,6750000.0,Working,Higher education,Married,House / apartment,-19341,-443,1,1,1,0,Laborers,2.0,52,1
228164,5987969,M,Y,N,0,6750000.0,Working,Higher education,Married,House / apartment,-19341,-443,1,1,1,0,Laborers,2.0,52,1
421262,7987964,M,Y,N,0,6750000.0,Working,Higher education,Married,House / apartment,-19341,-443,1,1,1,0,Laborers,2.0,52,1

In [43]:
df.groupby('OCCUPATION_TYPE')['AMT_INCOME_TOTAL'].idxmax()

OCCUPATION_TYPE
Accountants              230067
Cleaning staff           144185
Cooking staff             48476
Core staff               380243
Drivers                    9752
HR staff                  23309
High skill tech staff    346046
IT staff                 156058
Laborers                 228159
Low-skill Laborers       198297
Managers                 282687
Medicine staff           226665
Private service staff    369564
Realty agents            187872
Sales staff              418676
Secretaries              240910
Security staff            48224
Waiters/barmen staff     402262
Name: AMT_INCOME_TOTAL, dtype: int64

In [44]:
df['Age'].corr(df['AMT_INCOME_TOTAL'])

np.float64(-0.05386481327000893)

In [46]:
df.groupby('CODE_GENDER')['AMT_INCOME_TOTAL'].mean()

CODE_GENDER
F    174523.040910
M    214086.638868
Name: AMT_INCOME_TOTAL, dtype: float64