In [3]:
import pandas as pd
import numpy as np

In [4]:
pd.set_option("display.max_columns",None)
pd.set_option("display.max_rows",None)

In [5]:
df=pd.read_csv("bina.az_cleaned.csv")
df.head()

,id_x,rel_url,price,location,city,day_x,hour_x,vip,featured,products_label,img_url,id_y,description,unit_price,owner_name,owner_title,shop_name,address,lat,lng,updated,views,Kateqoriya,Otaq sayı,Sahə (m²),Torpaq sahəsi,Təmir,Çıxarış,İpoteka,estate_rel_url,extra_info,Current_floor,Total_floor,Area_per_room,district
0,5df36281-6dc6-4d5d-89a7-5fcfa86f7608,/alqi-satqi?page=174,499999.0,Səbail r.,bakı,2024-10-05,23:52,1,1,Private,https://bina.azstatic.com/uploads/f460x345/202...,92e82ea2-e1f3-4c2d-a284-151efd99281e,"Səbail Rayonu, İzzət Nəbiyev küçəsi, Fəxri Xiy...",3450.000000,Kamran,mülkiyyətçi,Fiziki sexs,İzzət Nəbiyev küç.,40.358817,49.824092,yeniləndi: dünən 23:52,1155,Köhnə tikili,4.0,145.0,NaN,var,var,0,/items/4521724,Şəhidlər xiyabanı * Dağüstü parkı * Səbail r.,7.0,9.0,36.25,Səbail r.
1,883e20f0-8872-49a5-8b4b-63b8301b5f8f,/alqi-satqi?page=250,77000.0,Biləcəri q.,bakı,2024-10-05,23:56,0,0,Private,https://bina.azstatic.com/uploads/f460x345/202...,505eaf81-6bc8-4094-9b00-aa82066548ee,"Biləcəridə Abidəyə yaxin 91,92,202 saylı marşr...",855.555556,Dasinmaz Emlak,vasitəçi (agent),Fiziki sexs,Biləcəri qəs.,40.420897,49.807035,yeniləndi: 04 oktyabr 2024,218,Həyət evi/Bağ evi,4.0,90.0,1.3,var,yoxdur,0,/items/4669294,Binəqədi r.* Biləcəri q.,NaN,NaN,22.50,Binəqədi r.
2,55c36fb1-a3af-476e-ba17-a81f6795be8d,/alqi-satqi?page=250,92000.0,İnşaatçılar m.,bakı,2024-10-05,23:55,0,0,Private,https://bina.azstatic.com/uploads/f460x345/202...,fa63b201-999d-43b5-a61a-778d9d79a6c6,Salam əleykum. \nİnşaatçılar metrosuna yaxın m...,1533.333333,Məhəmməd,vasitəçi (agent),Fiziki sexs,Mirzə Cabbar Məmmədzadə küç.,40.390293,49.802656,yeniləndi: 04 oktyabr 2024,190,Həyət evi/Bağ evi,3.0,60.0,0.1,var,var,0,/items/4669293,İnşaatçılar m.* Yasamal r.,NaN,NaN,20.00,Yasamal r.
3,acf1aa8d-a46a-40f5-b6f2-f7a449569337,/alqi-satqi?page=250,95000.0,Qaraçuxur q.,bakı,2024-10-05,23:55,1,1,Private,https://bina.azstatic.com/uploads/f460x345/202...,5db56980-05cc-4925-b55b-f58fb3f4d2b6,Barter maraqlidir üstünlük maşina verilir\nHər...,730.769231,Elçin,mülkiyyətçi,Fiziki sexs,Qaraçuxur qəs.,40.393614,49.981553,yeniləndi: 04 oktyabr 2024,1314,Obyekt,NaN,130.0,NaN,var,var,1,/items/4647811,Suraxanı r.* Qaraçuxur q.,NaN,NaN,NaN,Suraxanı r.
4,22d840df-9283-4112-bc71-7432511fc776,/alqi-satqi?page=250,220000.0,Əhmədli m.,bakı,2024-10-05,23:52,0,0,Agentlik,https://bina.azstatic.com/uploads/f460x345/202...,d71cf9a9-86dd-4162-b540-6252a8659a09,Əhmədli qəs. Qaçaq Nəbi küçəsi 3 otaga duzelm...,2200.000000,Dürdanə,vasitəçi (agent),Elite Ofis,Qaçaq Nəbi küç.,40.390550,49.957675,yeniləndi: 04 oktyabr 2024,240,Yeni tikili,3.0,100.0,NaN,var,var,0,/items/4638863,Əhmədli m.* Xalqlar Dostluğu m.* Xətai r.* Əhm...,15.0,16.0,33.33,Xətai r.

In [6]:
df.shape

(99767, 35)

In [7]:
df.describe()

,price,vip,featured,unit_price,lat,lng,views,Otaq sayı,Sahə (m²),Torpaq sahəsi,İpoteka,Current_floor,Total_floor,Area_per_room
count,9.976700e+04,99767.000000,99767.000000,99767.000000,99767.000000,99767.000000,99767.000000,91186.000000,99767.000000,15471.00000,99767.000000,75909.000000,75909.000000,91186.000000
mean,2.871309e+05,0.085038,0.031092,2246.686321,40.410870,49.886605,671.383794,3.125929,219.031793,11.52027,0.327303,7.847791,13.544481,37.883969
std,3.036363e+05,0.278940,0.173568,2089.387299,0.082027,0.265756,1525.817245,1.357527,2541.335600,299.45797,0.469231,4.881644,5.437074,14.497751
min,1.100000e+01,0.000000,0.000000,0.050000,32.689217,12.591688,23.000000,1.000000,1.000000,0.10000,0.000000,1.000000,1.000000,0.250000
25%,1.440000e+05,0.000000,0.000000,1680.000000,40.382008,49.816489,99.000000,2.000000,70.000000,2.50000,0.000000,4.000000,9.000000,28.750000
50%,2.150000e+05,0.000000,0.000000,2210.000000,40.397287,49.852921,251.000000,3.000000,104.000000,4.00000,0.000000,7.000000,16.000000,35.500000
75%,3.300000e+05,0.000000,0.000000,2720.000000,40.420564,49.949173,668.000000,4.000000,157.000000,6.50000,1.000000,11.000000,17.000000,45.000000
max,8.000000e+06,1.000000,1.000000,380000.000000,41.774687,50.341059,113458.000000,20.000000,700000.000000,36000.00000,1.000000,27.000000,33.000000,1000.000000

In [8]:
q_low = df['Sahə (m²)'].quantile(0.005)
q_high = df['Sahə (m²)'].quantile(0.995)
print(f"Sahə (m²) clip range: {q_low:.1f} - {q_high:.1f}")
df = df[(df['Sahə (m²)'] >= q_low) & (df['Sahə (m²)'] <= q_high)]

p_low = df['price'].quantile(0.005)
p_high = df['price'].quantile(0.995)
print(f"price clip range: {p_low:.1f} - {p_high:.1f}")
df = df[(df['price'] >= p_low) & (df['price'] <= p_high)]

Sahə (m²) clip range: 30.0 - 3000.0
price clip range: 16000.0 - 2000000.0

In [9]:
df.shape

(97968, 35)

In [10]:
df["Çıxarış"] = df["Çıxarış"].map({
    "yoxdur": 0,
    "var": 1
})

In [11]:
df['Çıxarış'].value_counts()

Çıxarış
1    77150
0    20818
Name: count, dtype: int64

In [12]:
df['Çıxarış'].dtypes

dtype('int64')

In [13]:
X=df.drop('Çıxarış',axis=1)
y=df['Çıxarış']

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=42)

In [22]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import RobustScaler,OneHotEncoder,TargetEncoder,FunctionTransformer
from sklearn.compose import ColumnTransformer
from sklearn.metrics import classification_report,roc_auc_score
from sklearn.model_selection import cross_val_score

log_cols=['Sahə (m²)','Torpaq sahəsi','Area_per_room','price']
num_cols=['lat','lng','Otaq sayı','Total_floor','Current_floor']
targ_cols=['location','shop_name']
ohe_cols=['city','district','products_label','owner_title','Kateqoriya','Təmir','İpoteka']

log_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy='constant',fill_value=0)),
    ('log',FunctionTransformer(func=np.log1p,inverse_func=np.expm1,feature_names_out = 'one-to-one',check_inverse=False)),
    ('scaler',RobustScaler())
])

num_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy='constant',fill_value=0)),
    ('scaler',RobustScaler())
])

targ_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy='constant',fill_value='unknown')),
    ('encoder',TargetEncoder(target_type='binary'))
])

ohe_pipeline = Pipeline([
    ('imputer',SimpleImputer(strategy='constant',fill_value='unknown')),
    ('encoder',OneHotEncoder(handle_unknown='ignore',sparse_output=False))
])

preprocessing = ColumnTransformer([
    ('log',log_pipeline,log_cols),
    ('num',num_pipeline,num_cols),
    ('targ',targ_pipeline,targ_cols),
    ('ohe',ohe_pipeline,ohe_cols)
],
 remainder='drop')

In [28]:
from sklearn.linear_model import LogisticRegression

log_reg = Pipeline([
    ('preprocessing', preprocessing),
    ('model', LogisticRegression(max_iter=1000,class_weight='balanced'))
])
log_reg.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('log',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value=0,
                                                                                 strategy='constant')),
                                                                  ('log',
                                                                   FunctionTransformer(check_inverse=False,
                                                                                       feature_names_out='one-to-one',
                                                                                       func=<ufunc 'log1p'>,
                                                                                       inverse_func=<ufunc 'expm1'>)),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['Sahə (m²)', 'Torpaq sahəsi',
                                                   'Area_per_room', 'pr...
                                                                   TargetEncoder(target_type='binary'))]),
                                                  ['location', 'shop_name']),
                                                 ('ohe',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='unknown',
                                                                                 strategy='constant')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['city', 'district',
                                                   'products_label',
                                                   'owner_title', 'Kateqoriya',
                                                   'Təmir', 'İpoteka'])])),
                ('model',
                 LogisticRegression(class_weight='balanced', max_iter=1000))])

In [29]:
log_reg.predict_proba(X_test)

array([[0.23378929, 0.76621071],
       [0.0242509 , 0.9757491 ],
       [0.04062695, 0.95937305],
       ...,
       [0.02689466, 0.97310534],
       [0.02712807, 0.97287193],
       [0.92056737, 0.07943263]])

In [30]:
y_pred_testl = log_reg.predict(X_test)
result_testl = classification_report(y_test, y_pred_testl)
print(result_testl)
print(roc_auc_score(y_test,y_pred_testl))

              precision    recall  f1-score   support

           0       0.51      0.92      0.65      4158
           1       0.97      0.76      0.85     15436

    accuracy                           0.79     19594
   macro avg       0.74      0.84      0.75     19594
weighted avg       0.87      0.79      0.81     19594

0.8390243206257718

In [31]:
y_pred_trainl = log_reg.predict(X_train)
result_trainl = classification_report(y_train, y_pred_trainl)
print(result_trainl)
print(roc_auc_score(y_train,y_pred_trainl))

              precision    recall  f1-score   support

           0       0.51      0.92      0.66     16660
           1       0.97      0.76      0.85     61714

    accuracy                           0.80     78374
   macro avg       0.74      0.84      0.76     78374
weighted avg       0.87      0.80      0.81     78374

0.8412744022974585

In [32]:
scores_log = cross_val_score(
    log_reg,
    X_train,
    y_train,
    cv=5,
    scoring='f1',
    n_jobs=-1
)

print(scores_log)
print("Mean f1:", scores_log.mean())

[0.85216521 0.85203385 0.85479701 0.85149325 0.85562372]
Mean f1: 0.8532226081589679

In [24]:
from sklearn.ensemble import RandomForestClassifier

rf_model = Pipeline([
    ('preprocessing', preprocessing),
    ('model', RandomForestClassifier(
        n_estimators=200,
        random_state=42,
        class_weight='balanced',
        n_jobs=-1
    ))
])

rf_model.fit(X_train, y_train)

Pipeline(steps=[('preprocessing',
                 ColumnTransformer(transformers=[('log',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value=0,
                                                                                 strategy='constant')),
                                                                  ('log',
                                                                   FunctionTransformer(check_inverse=False,
                                                                                       feature_names_out='one-to-one',
                                                                                       func=<ufunc 'log1p'>,
                                                                                       inverse_func=<ufunc 'expm1'>)),
                                                                  ('scaler',
                                                                   RobustScaler())]),
                                                  ['Sahə (m²)', 'Torpaq sahəsi',
                                                   'Area_per_room', 'pr...
                                                 ('ohe',
                                                  Pipeline(steps=[('imputer',
                                                                   SimpleImputer(fill_value='unknown',
                                                                                 strategy='constant')),
                                                                  ('encoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  ['city', 'district',
                                                   'products_label',
                                                   'owner_title', 'Kateqoriya',
                                                   'Təmir', 'İpoteka'])])),
                ('model',
                 RandomForestClassifier(class_weight='balanced',
                                        n_estimators=200, n_jobs=-1,
                                        random_state=42))])

In [35]:
y_pred_testrf = rf_model.predict(X_test)
result_testrf = classification_report(y_test, y_pred_testrf)
print(result_testrf)
print(roc_auc_score(y_test,y_pred_testrf))

              precision    recall  f1-score   support

           0       0.90      0.85      0.88      4158
           1       0.96      0.98      0.97     15436

    accuracy                           0.95     19594
   macro avg       0.93      0.91      0.92     19594
weighted avg       0.95      0.95      0.95     19594

0.9125023947192904

In [42]:
y_pred_trainrf = rf_model.predict(X_train)
result_trainrf = classification_report(y_train, y_pred_trainrf)
print(result_trainrf)
print(roc_auc_score(y_train,y_pred_trainrf))

              precision    recall  f1-score   support

           0       0.99      0.98      0.99     16660
           1       1.00      1.00      1.00     61714

    accuracy                           0.99     78374
   macro avg       0.99      0.99      0.99     78374
weighted avg       0.99      0.99      0.99     78374

0.9904533570241786

In [38]:
scores_rf = cross_val_score(
    rf_model,
    X_train,
    y_train,
    cv=5,
    scoring='f1',
    n_jobs=-1
)

print(scores_rf)
print("Mean f1:", scores_rf.mean())

[0.96276127 0.96380998 0.96352474 0.96387185 0.96487363]
Mean f1: 0.9637682945489597

In [44]:
from sklearn.model_selection import RandomizedSearchCV
from scipy.stats import randint

# ── Axtarılacaq parametr aralığı ──────────────────────────
param_dist = {
    'model__n_estimators':      randint(100, 500),
    'model__max_depth':         [5, 8, 10, 15, 20, None],
    'model__min_samples_leaf':  randint(1, 20),
    'model__min_samples_split': randint(2, 20),
    'model__max_features':      ['sqrt', 'log2', 0.3, 0.5],
}

# ── RandomizedSearchCV ─────────────────────────────────────
random_search = RandomizedSearchCV(
    estimator=rf_model,        # sənin pipeline-ın
    param_distributions=param_dist,
    n_iter=30,                 # 30 fərqli kombinasiya sınayır
    cv=3,                      # 3-fold cross-validation
    scoring='f1',              # imbalanced data üçün f1 daha yaxşı
    n_jobs=-1,
    random_state=42,
    verbose=2,                 # progress göstərir
)

random_search.fit(X_train, y_train)

# ── Nəticə ────────────────────────────────────────────────
print("Ən yaxşı parametrlər:")
print(random_search.best_params_)
print(f"\nCross-val F1: {random_search.best_score_:.4f}")

# ── Ən yaxşı modeli götür ──────────────────────────────────
best_rf = random_search.best_estimator_

# ── Train vs Test yoxla ────────────────────────────────────
print("\nTrain:")
print(classification_report(y_train, best_rf.predict(X_train)))

print("\nTest:")
print(classification_report(y_test, best_rf.predict(X_test)))

Fitting 3 folds for each of 30 candidates, totalling 90 fits

/usr/local/lib/python3.12/dist-packages/joblib/externals/loky/process_executor.py:782: UserWarning: A worker stopped while some jobs were given to the executor. This can be caused by a too short worker timeout or by a memory leak.
  warnings.warn(

Ən yaxşı parametrlər:
{'model__max_depth': None, 'model__max_features': 0.3, 'model__min_samples_leaf': 1, 'model__min_samples_split': 6, 'model__n_estimators': 317}

Cross-val F1: 0.9587

Train:
              precision    recall  f1-score   support

           0       0.97      0.98      0.97     16660
           1       0.99      0.99      0.99     61714

    accuracy                           0.99     78374
   macro avg       0.98      0.98      0.98     78374
weighted avg       0.99      0.99      0.99     78374


Test:
              precision    recall  f1-score   support

           0       0.87      0.87      0.87      4158
           1       0.97      0.97      0.97     15436

    accuracy                           0.95     19594
   macro avg       0.92      0.92      0.92     19594
weighted avg       0.95      0.95      0.95     19594